languageCode: en-gb
title: Peter Möstl
baseurl: 'https://www.gartenastrofotos.de/'
theme: wip
pagination.pagerSize: 10
enableRobotsTXT: true
MetaDataFormat: yaml
pygmentsCodefences: true
pygmentsUseClasses: true
pluralizelisttitles: "false"
enableGitInfo: true
timeout: 2m # extended for image processing
permalinks:
  post: '/:year/:month/:day/:title/'

frontmatter:
  lastmod:
  - lastmod
  - :git
  - date
  - publishDate

# Theme parameters
params:
  author:
    name: Peter
    email: peter.moestl@gmx.de
  displayTitle: false
  description: astrophotography, linux
  copyright: "Copyright © 2023, 2024 Peter Möstl"
  photoLicense: CC BY-NC-ND 4.0
  avatar: img/avatar.jpg
  showUpdated: true
  menuOnIndex: false
  mainSections:
    - post
    - watch
    - travel
  webmention:
    baseURL: https://www.gartenastrofotos.de/
    server: https://webmention.io/api/mentions.jf2
  relMe:
    mastodon: https://social.tchncs.de/@petmos


# Use a menu rather than a generated list of sections to avoid
# odd naming issues with pluralisation.
menu:
  main:
    - name: home
      url: /
      weight: 10
    - name: blog
      url: /posts/
      weight: 20
    - name: notes
      url: /notes/
      weight: 30
    - name: equipment
      url: /equipment/
      weight: 35
    - name: Astrophotography
      url: /photos/
      weight: 36
    - name: tags
      url: /tags/
      weight: 40
    - name: contact
      url: /contact/
      weight: 50
  index:
    - name: blog
      url: /posts/
      weight: 10
    - name: notes
      url: /notes/
      weight: 20
    - name: equipment
      url: /equipment/
      weight: 25
    - name: Astrophotography
      url: /photos/
      weight: 26
    - name: tags
      url: /tags/
      weight: 30
    - name: contact
      url: /contact/
      weight: 40

social:
  rss-square: /index.xml
  mastodon: 'https://social.tchncs.de/@petmos'
taxonomies:
  tag: tags
  category: categories
  series: series
markup:
  goldmark:
    renderer:
      unsafe: true

imaging:
  exif:
    disableDate: false
    disableLatLong: true
    excludeFields: ""
    includeFields: ".*"
